# Generated by Django 3.0.8 on 2020-08-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admission',
        ),
        migrations.DeleteModel(
            name='AdmissionModel',
        ),
    ]
