# Generated by Django 3.0.8 on 2020-08-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0002_auto_20200809_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Student_Name', models.CharField(max_length=100)),
                ('Class_Name', models.IntegerField()),
                ('Previous_School', models.CharField(max_length=100)),
                ('Father_Name', models.CharField(max_length=100)),
                ('Mother_Name', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('State', models.CharField(choices=[('', 'Any'), ('BR', 'BIHAR'), ('UP', 'Uttar Pradesh'), ('MP', 'Madhya Pradesh')], max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('RollNo', models.IntegerField()),
            ],
        ),
    ]
