# Generated by Django 3.0.8 on 2020-08-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0003_admission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='RollNo',
            field=models.IntegerField(null=True),
        ),
    ]
