# Generated by Django 3.0.8 on 2020-09-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0004_auto_20200809_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Student_Name', models.CharField(max_length=100)),
                ('Question', models.CharField(max_length=1000)),
                ('Answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Message',
            field=models.TextField(max_length=1000),
        ),
    ]
