# Generated by Django 3.0.8 on 2020-09-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0005_auto_20200911_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Upload',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Question_file', models.FileField(upload_to='Documents/')),
            ],
        ),
    ]
