# Generated by Django 3.0.8 on 2020-09-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0006_exam_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID',models.IntegerField(primary_key=True)),
                ('Question', models.CharField(max_length=1000)),
                ('Option1', models.CharField(max_length=100)),
                ('Option2', models.CharField(max_length=100)),
                ('Option3', models.CharField(max_length=100)),
                ('Option4', models.CharField(max_length=100)),
            ],
        ),
    ]
