# Generated by Django 3.0.8 on 2020-09-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0007_questions_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions_model',
            name='id',
        ),
        migrations.AlterField(
            model_name='questions_model',
            name='Id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
