# Generated by Django 3.0.8 on 2020-09-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0008_auto_20200912_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions_model',
            name='Id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
