# Generated by Django 3.0.8 on 2020-09-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0009_questions_model_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Question', models.CharField(max_length=1000)),
                ('Option1', models.CharField(max_length=100)),
                ('Option2', models.CharField(max_length=100)),
                ('Option3', models.CharField(max_length=100)),
                ('Option4', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Questions_Model',
        ),
    ]
