# Generated by Django 3.0.8 on 2020-09-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0010_auto_20200912_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Answer', models.CharField(max_length=100)),
            ],
        ),
    ]
